for_loop:
  for_loop:
    - "Rubyists tend to prefer enumerable methods over for loops. The most basic choice is Enumerable#each, but there are many others that you might want to choose, depending on what you're trying to do. Check out http://ruby-doc.org/core-2.1.2/Enumerable.html) to see what's available."